function sparkline(rows){const values=rows.slice(-60).map(r=>r.close).filter(v=>v!=null);if(values.length<2)return'';const w=600,h=84,min=Math.min(...values),max=Math.max(...values),range=max-min||1;const points=values.map((v,i)=>`${i/(values.length-1)*w},${h-(v-min)/range*(h-8)-4}`).join(' '),area=`0,${h} ${points} ${w},${h}`;return`<svg class="sparkline" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polygon class="area" points="${area}"></polygon><polyline points="${points}"></polyline></svg>`}
function probabilitySection(f){return`<div class="prob-grid"><div class="prob-box"><small class="muted">上漲機率</small><b class="up">${f.up}%</b><div class="progress"><span class="bar-up" style="width:${f.up}%"></span></div></div><div class="prob-box"><small class="muted">震盪機率</small><b class="neutral">${f.neutral}%</b><div class="progress"><span class="bar-neutral" style="width:${f.neutral}%"></span></div></div><div class="prob-box"><small class="muted">下跌機率</small><b class="down">${f.down}%</b><div class="progress"><span class="bar-down" style="width:${f.down}%"></span></div></div></div>`}
function factorSection(f){const rows=[['技術面',f.technical,55],['基本面',f.fundamental,35],['籌碼面',f.chip,20],['估值面',f.valuation,15]];return`<div class="factor-list">${rows.map(([label,value,max])=>`<div class="factor"><span>${label}</span><div class="track"><span style="width:${clamp((value+max)/(max*2)*100,0,100)}%"></span></div><b class="${cls(value)}">${value>0?'+':''}${fmt(value,1)}</b></div>`).join('')}</div>`}
function scenarioHtml(stock,forecast,indicators){return scenarioAnalysis(stock,forecast,indicators).map(s=>`<div class="card scenario ${s.type}"><div class="head"><div><b>${s.title}</b><div class="muted">觸發條件：${s.trigger}</div></div><b>${s.prob}%</b></div><div class="price">${fmt(s.range[0])}～${fmt(s.range[1])}</div><div class="muted">5 個交易日情境區間，非價格保證。</div></div>`).join('')}
function marketIndustryHtml(stock){const env=marketEnvironment(),industry=env.industries.find(x=>x.industry===stock.industry);return`<div class="grid">${metric('大盤環境',env.label)}${metric('多頭家數比',`${fmt(env.breadth,0)}%`)}${metric(`${stock.industry}平均漲跌`,industry?pct(industry.avgChange):reasonDash('同業不足'))}${metric(`${stock.industry}上漲家數`,industry?`${fmt(industry.breadth,0)}%`:reasonDash('同業不足'))}${metric('市場外資合計',`${fmt(env.foreign,0)} 張`)}${metric('產業外資合計',industry?`${fmt(industry.foreign,0)} 張`:reasonDash('同業不足'))}</div>`}
function peerHtml(stock){const peer=peerComparison(stock);return`<div class="card"><div class="muted">比較群組：${stock.industry}，共 ${peer.peerCount} 檔可比較股票</div>${peer.rows.map(r=>`<div class="peer-row"><span>${r.label}</span><div><div class="peer-track"><span style="width:${r.percentile??0}%"></span></div><small class="muted">同業中位數 ${r.median==null?'—':`${fmt(r.median)}${r.suffix}`}</small></div><b>${r.value==null?'—':`${fmt(r.value)}${r.suffix}`}<br><small class="muted">前 ${r.percentile==null?'—':100-r.percentile+1}%</small></b></div>`).join('')}</div>`}
function eventHtml(stock,indicators){const events=buildEvents(stock,indicators);return`<div class="card">${events.map(e=>`<div class="event"><div class="event-icon">${e.icon}</div><div><b>${e.title}</b><div class="muted">${e.detail}</div></div><span class="tag ${e.level==='bad'?'bad':e.level==='warn'?'warn':'info'}">${e.level==='bad'?'風險':e.level==='warn'?'注意':'事件'}</span></div>`).join('')}</div>`}

function detailHtml(stock,state){
  const indicators=state?.indicators||null,history=state?.rows||[],forecast=calculateForecast(stock,indicators);
  const historyLoading=state?.loading,historyError=state?.error;
  return`<div class="modal"><div class="sheet"><button class="sheet-close" type="button">×</button><div class="head"><div><h2>${stock.name} ${stock.symbol}</h2><div class="muted">${stock.market} · ${stock.industry} · ${S.date}</div></div><button class="btn secondary small-btn" data-watch="${stock.symbol}">${isWatched(stock.symbol)?'★ 已自選':'☆ 加入自選'}</button></div><div><span class="price">${fmt(stock.close)} 元</span> <b class="${cls(stock.change)}">${pct(stock.change)}</b></div>
  ${historyLoading?'<div class="card"><div class="loading"><span class="spinner"></span>正在讀取歷史日線並計算技術指標…</div></div>':''}${historyError?`<div class="card warn-card"><b>歷史日線暫時無法取得</b><p class="muted">目前先使用基本面與籌碼進行低信心估計。${esc(historyError)}</p></div>`:''}${history.length?sparkline(history):''}
  <h3 class="section-title">未來漲跌預測（5 個交易日）</h3><div class="card accent"><div class="head"><div><small class="muted">判斷</small><div class="price">${forecast.shortLabel}</div><div class="muted">中期：${forecast.mediumLabel}</div></div><div><small class="muted">預測信心</small><div class="score">${forecast.confidence}%</div><div class="muted">資料完整度 ${forecast.completeness}%</div></div></div>${probabilitySection(forecast)}<div class="grid" style="margin-top:10px">${metric('5 日合理波動區間',`${fmt(forecast.expectedLow)}～${fmt(forecast.expectedHigh)}`,`推估 ±${fmt(forecast.expectedMove5,1)}%`)}${metric('綜合方向分數',`${forecast.composite>0?'+':''}${forecast.composite}`,'正值偏多、負值偏空')}</div></div><div class="notice"><b>僅供參考使用</b><br>${DISCLAIMER}</div>
  <h3 class="section-title">三種情境分析</h3>${scenarioHtml(stock,forecast,indicators)}
  <h3 class="section-title">大盤與產業環境</h3><div class="card">${marketIndustryHtml(stock)}</div>
  <h3 class="section-title">同業比較</h3>${peerHtml(stock)}
  <h3 class="section-title">重要事件與風險提醒</h3>${eventHtml(stock,indicators)}
  <h3 class="section-title">評估構成</h3><div class="card">${factorSection(forecast)}</div><div class="card"><h3>支持因素</h3>${forecast.positive.length?forecast.positive.map(x=>`<span class="tag">${x}</span>`).join(''):'<span class="muted">目前沒有明顯正向訊號</span>'}<h3 style="margin-top:14px">風險因素</h3>${forecast.negative.length?forecast.negative.map(x=>`<span class="tag warn">${x}</span>`).join(''):'<span class="muted">目前沒有明顯負向訊號</span>'}<h3 style="margin-top:14px">資料缺口</h3>${forecast.missing.length?forecast.missing.map(x=>`<span class="tag bad">${x}</span>`).join(''):'<span class="tag">主要資料完整</span>'}</div>
  <h3 class="section-title">技術面分析</h3><div class="grid three">${metric('MA5',valueOrReason(indicators?.ma5))}${metric('MA20',valueOrReason(indicators?.ma20))}${metric('MA60',valueOrReason(indicators?.ma60))}${metric('RSI 14',valueOrReason(indicators?.rsi14))}${metric('MACD',valueOrReason(indicators?.macd))}${metric('MACD 柱狀體',valueOrReason(indicators?.histogram))}${metric('ATR 14',valueOrReason(indicators?.atr14),indicators?.atrPct!=null?`${fmt(indicators.atrPct)}%`:'')}${metric('量能比 5/20',valueOrReason(indicators?.volumeRatio,' 倍'))}${metric('20 日動能',valueOrReason(indicators?.momentum20,'%'))}${metric('布林上軌',valueOrReason(indicators?.bollingerUpper))}${metric('布林中軌',valueOrReason(indicators?.bollingerMiddle))}${metric('布林下軌',valueOrReason(indicators?.bollingerLower))}${metric('20 日支撐',valueOrReason(indicators?.support))}${metric('20 日壓力',valueOrReason(indicators?.resistance))}${metric('歷史日線筆數',indicators?.rows==null?reasonDash('尚未取得'):fmt(indicators.rows,0))}</div>
  <h3 class="section-title">基本面與估值</h3><div class="grid three">${metric('本益比',valueOrReason(stock.pe))}${metric('股價淨值比',valueOrReason(stock.pb))}${metric('殖利率',valueOrReason(stock.yield,'%'))}${metric('當月營收',stock.revenue==null?reasonDash('API 未回傳'):`${fmt(stock.revenue/1000,0)} 百萬元`,stock.revPeriod||'')}${metric('月營收年增',pct(stock.rev))}${metric('月營收月增',pct(stock.revMom))}${metric('累計營收年增',pct(stock.revYtd))}${metric('EPS',valueOrReason(stock.eps))}${metric(stock.roeEstimated?'年化推估 ROE':'ROE',valueOrReason(stock.roe,'%'),stock.roePeriod||'')}${metric('毛利率',valueOrReason(stock.grossMargin,'%'))}${metric('營業利益率',valueOrReason(stock.operatingMargin,'%'))}${metric('淨利率',valueOrReason(stock.netMargin,'%'))}${metric('負債比',valueOrReason(stock.debt,'%'))}${metric('權益比率',valueOrReason(stock.equityRatio,'%'))}${metric('資料期間',stock.roePeriod||stock.revPeriod||'—')}</div>${stock.roeEstimated?'<div class="notice">ROE 是依最新公開累計淨利與股東權益推算的年化值，並非官方直接公布的單一指標。</div>':''}
  <h3 class="section-title">籌碼與交易資訊</h3><div class="grid three">${metric('外資買賣超',stock.foreign==null?reasonDash('當日 API 無資料'):`${fmt(stock.foreign,0)} 張`)}${metric('投信買賣超',stock.trust==null?reasonDash('當日 API 無資料'):`${fmt(stock.trust,0)} 張`)}${metric('自營商買賣超',stock.dealer==null?reasonDash('當日 API 無資料'):`${fmt(stock.dealer,0)} 張`)}${metric('三大法人合計',stock.inst==null?reasonDash('當日 API 無資料'):`${fmt(stock.inst,0)} 張`)}${metric('融資增減',stock.marginChange==null?reasonDash('API 未回傳'):`${fmt(stock.marginChange,0)} 張`)}${metric('融資餘額',stock.marginBalance==null?reasonDash('API 未回傳'):`${fmt(stock.marginBalance,0)} 張`)}${metric('融券增減',stock.shortChange==null?reasonDash('API 未回傳'):`${fmt(stock.shortChange,0)} 張`)}${metric('融券餘額',stock.shortBalance==null?reasonDash('API 未回傳'):`${fmt(stock.shortBalance,0)} 張`)}${metric('成交量',stock.volume==null?reasonDash('API 未回傳'):`${fmt(stock.volume,0)} 張`)}${metric('開盤',valueOrReason(stock.open))}${metric('最高',valueOrReason(stock.high))}${metric('最低',valueOrReason(stock.low))}${metric('成交金額',stock.value==null?reasonDash('API 未回傳'):`${fmt(stock.value/100000000,2)} 億元`)}${metric('成交筆數',stock.transactions==null?reasonDash('API 未回傳'):fmt(stock.transactions,0))}${metric('收盤',valueOrReason(stock.close))}</div>
  <div class="row" style="margin-top:16px"><button class="btn grow" data-journal-stock="${stock.symbol}">新增投資紀錄</button><button class="btn secondary" data-verify-stock="${stock.symbol}">查看預測驗證</button></div>${disclaimer()}</div></div>`
}

async function openDetail(symbol,loadHistory=true){
  const stock=S.stocks.find(x=>x.symbol===symbol);if(!stock)return;S.detailSymbol=symbol;const cached=S.historyCache.get(symbol),resolved=cached&&!(cached instanceof Promise)?cached:null;
  modalRoot.innerHTML=detailHtml(stock,resolved?{...resolved,loading:false}:{loading:loadHistory,rows:[]});bindModal();if(!loadHistory&&!cached)return;if(resolved){const f=calculateForecast(stock,resolved.indicators);recordPrediction(stock,f);evaluatePredictionsForSymbol(symbol,resolved.rows);return}
  try{const result=await getHistory(symbol);if(S.detailSymbol!==symbol)return;modalRoot.innerHTML=detailHtml(stock,{...result,loading:false});bindModal();const f=calculateForecast(stock,result.indicators);recordPrediction(stock,f);evaluatePredictionsForSymbol(symbol,result.rows)}catch(error){if(S.detailSymbol!==symbol)return;modalRoot.innerHTML=detailHtml(stock,{loading:false,error:error.message,rows:[]});bindModal();recordPrediction(stock,calculateForecast(stock,null))}
}
function closeModal(){S.detailSymbol=null;modalRoot.innerHTML=''}
